set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 50000
set -g @scroll-without-changing-pane on # 휠 카피모드 비활성화

# Leader 키 변경
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# pane 분할 (WezTerm과 동일: D=좌우, E=위아래)
bind d split-window -h -c "#{pane_current_path}"
bind e split-window -v -c "#{pane_current_path}"

# pane 닫기
bind w kill-pane

# pane 이동 (WezTerm과 동일: 방향키)
bind Left  select-pane -L
bind Right select-pane -R
bind Up    select-pane -U
bind Down  select-pane -D

# detach
bind q detach

# kill-session
bind x kill-session